Exception: separate the "backtrace" from the `what()`
* `backtrace()` is now a static function that has nothing to do with the current
  exception or `noa::Exception`s. It is simpler to use since it returns a vector
  that user can parse easily.

Tags: [refactor]
Compile: yes
Tests: yes